version: 2
jobs:
  build:
    docker:
      - image: trieuvi/sculpt:v2
    working_directory: /var/www/drsculpt
    steps:
      - checkout
      - run: cp .env.example .env

      # composer cache
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
      - run:  composer install
      - save_cache:
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # run basic unit test
      - run: ./vendor/bin/phpunit
