version: 2
jobs:
  build:
    docker:
      - image: trieuvi/sculpt:v2
    working_directory: /var/www/drsculpt
    steps:
      - checkout
      - run: cp .env.example .env

      # composer cache
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
      - run:  composer install
      - save_cache:
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # run basic unit test
      - run: ./vendor/bin/phpunit
  deploy-heroku:
    docker:
      - image: trieuvi/sculpt:v2
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git config --global push.default current
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git develop:master -f
  workflows:
    version: 2
    build-n-deploy:
      jobs:
        - build
        - deploy-heroku:
            requires:
              - build
            filters:
              branches:
                only:
                  - develop